services:
  - type: web
    name: smart-hub-backend
    runtime: node
    plan: free
    rootDir: ./backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_FILE
        value: ./src/database/tickets.db
      - key: ZOHOCREATOR_URL
        value: https://creator.zoho.in/api/v2.1/pk.08497121/smart-service-hub/form/Service_Hub_Form
      - key: ZOHOCREATOR_API_KEY
        value: 1000.25c23c1211c1a24d7ec02858086bd71a.b46f3786f76e8d09463db76471258ecc
