[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "echo 'No build step required for backend'"

[phases.start]
cmd = "node src/server.js"

[variables]
NODE_ENV = "production"